In [11]:
from pathlib import Path

from rich import print as print

from data.data_loader import config_loader, load_data
from data.processing import fetch_riders

import pandas as pd
import numpy as np

In [2]:
# Get the current working directory
cwd = Path.cwd()

# Navigate up two levels to get the project root
PROJECT_ROOT = cwd.parent
CONFIG_PATH = PROJECT_ROOT / "config/config.json"
DB_PATH = PROJECT_ROOT / "config/db_path.json"
print(CONFIG_PATH)

/Users/nealedgren/Erdos/grand_tours/config/config.json

In [3]:
# Enter tour, year of your choice
tour = "tdf"
year = 2023

# Gets the configuration json file needed for training models, hyperparameters. Check /config/config.json file.
config_path = Path(config_loader(tour, year, config_path=CONFIG_PATH))

# Load athletic training data
training_data = load_data(tour, year, db_path=DB_PATH, training=True, segment_data=False)
print(training_data)

print(
    f"The total number of riders in the race dataset is {len(fetch_riders(DB_PATH, tour, year))}."
)

Creating dataframe training:True

Error in move_time: 'move_time' in activity 8870676770.

Error in move_time: 'move_time' in activity 9361405382.

Error in move_time: 'move_time' in activity 9209116965.

Error in move_time: 'move_time' in activity 9117589400.

Error in move_time: 'move_time' in activity 9124971961.

Error in move_time: 'move_time' in activity 9220313847.

Error in move_time: 'move_time' in activity 8824823141.

Error in move_time: 'move_time' in activity 8861204865.

Error in move_time: 'move_time' in activity 8871998122.

Error in move_time: 'move_time' in activity 9220430194.

Error in move_time: 'move_time' in activity 9246305515.

Error in move_time: 'move_time' in activity 8846704202.

Error in move_time: 'move_time' in activity 9107873681.

Error in move_time: 'move_time' in activity 9113570810.

Error in move_time: 'move_time' in activity 9276803369.

Error in move_time: 'move_time' in activity 8952484194.

Error in move_time: 'move_time' in activity 9022173178.

Error in move_time: 'move_time' in activity 9145873747.

Error in move_time: 'move_time' in activity 9150270164.

Error in move_time: 'move_time' in activity 9156567623.

Error in move_time: 'move_time' in activity 9174192359.

Error in move_time: 'move_time' in activity 9162899454.

Error in move_time: 'move_time' in activity 9247190158.

Error in move_time: 'move_time' in activity 9220681689.

Error in move_time: 'move_time' in activity 9375840027.

Error in move_time: 'move_time' in activity 9375846023.

      strava_id  activity_id  distance  elevation  avg_power   time  \
0       4774417   8825469552    164.29     2516.0        NaN  14404
1       4774417   8835637609    191.93     3132.0        NaN  17583
2       4774417   8855739960    160.41     2564.0        NaN  13879
3       4774417   8856077206    173.84     3118.0        NaN  15754
4       4774417   8856083636    162.60     3183.0        NaN  14420
...         ...          ...       ...        ...        ...    ...
5090   18340568   9300606118     77.24     2443.0        NaN  11874
5091   18340568   9325910220    139.06     3939.0        NaN  20807
5092    5123163   8990988444     92.42      822.0      244.0  11039
5093    5123163   8996259200     58.33      435.0      242.0   5920
5094    5123163   9270587332    193.55     1746.0      271.0  16308

              tour_year  stage    ride_day race_start_day segments  time_delta
0     tdf_training-2023    NaN  2023-04-03     2023-07-01       []          89
1     tdf_training-2023    NaN  2023-04-04     2023-07-01       []          88
2     tdf_training-2023    NaN  2023-04-05     2023-07-01       []          87
3     tdf_training-2023    NaN  2023-04-06     2023-07-01       []          86
4     tdf_training-2023    NaN  2023-04-07     2023-07-01       []          85
...                 ...    ...         ...            ...      ...         ...
5090  tdf_training-2023    NaN  2023-06-20     2023-07-01       []          11
5091  tdf_training-2023    NaN  2023-06-24     2023-07-01       []           7
5092  tdf_training-2023    NaN  2023-05-01     2023-07-01       []          61
5093  tdf_training-2023    NaN  2023-05-02     2023-07-01       []          60
5094  tdf_training-2023    NaN  2023-06-15     2023-07-01       []          16

[5095 rows x 12 columns]

The total number of riders in the race dataset is 101.

In [ ]:
# Enter tour, year of your choice
tour = "tdf"
year = 2023

# Gets the configuration json file needed for training models, hyperparameters. Check /config/config.json file.
config_path = Path(config_loader(tour, year, config_path=CONFIG_PATH))

# Load racing data
race_data = load_data(tour, year, db_path=DB_PATH, training=False, segment_data=False)
print(race_data)

#print(
 #   f"The total number of riders in the race dataset is {len(fetch_riders(DB_PATH, tour, year))}."
#)

Creating dataframe training:False

Error in move_time: 'move_time' in activity 9474483817.

      strava_id  activity_id  distance  elevation  avg_power   time tour_year  \
0       4774417   9368886723    180.58       3262        NaN  15739  tdf-2023
1       4774417   9375430023    207.03       2240        NaN  17344  tdf-2023
2       4774417   9381093872    191.93       2394        NaN  16979  tdf-2023
3       4774417   9387946633    181.28       1499        NaN  15911  tdf-2023
4       4774417   9393653842    161.72       3369        NaN  14339  tdf-2023
...         ...          ...       ...        ...        ...    ...       ...
1755   18340568   9412475152    205.90       1951        NaN  16053  tdf-2023
1756   18340568   9419821663    191.83       3559        NaN  17440  tdf-2023
1757   18340568   9444280754    179.44       3091        NaN  15792  tdf-2023
1758   18340568   9450520126    159.89       2432        NaN  15062  tdf-2023
1759    5123163   9435838797    174.04       3071        NaN  15427  tdf-2023

         stage    ride_day race_start_day segments  time_delta
0      Stage 1  2023-07-01     2023-07-01       []           0
1      Stage 2  2023-07-02     2023-07-01       []          -1
2      Stage 3  2023-07-03     2023-07-01       []          -2
3      Stage 4  2023-07-04     2023-07-01       []          -3
4      Stage 5  2023-07-05     2023-07-01       []          -4
...        ...         ...            ...      ...         ...
1755   Stage 8  2023-07-08     2023-07-01       []          -7
1756   Stage 9  2023-07-09     2023-07-01       []          -8
1757  Stage 12  2023-07-13     2023-07-01       []         -12
1758  Stage 13  2023-07-14     2023-07-01       []         -13
1759  Stage 10  2023-07-11     2023-07-01       []         -10

[1760 rows x 12 columns]

In [7]:
race_data = race_data_23.copy()

In [8]:
print(race_data)
print(training_data)

      strava_id  activity_id  distance  elevation  avg_power   time tour_year  \
0       4774417   9368886723    180.58       3262        NaN  15739  tdf-2023
1       4774417   9375430023    207.03       2240        NaN  17344  tdf-2023
2       4774417   9381093872    191.93       2394        NaN  16979  tdf-2023
3       4774417   9387946633    181.28       1499        NaN  15911  tdf-2023
4       4774417   9393653842    161.72       3369        NaN  14339  tdf-2023
...         ...          ...       ...        ...        ...    ...       ...
1755   18340568   9412475152    205.90       1951        NaN  16053  tdf-2023
1756   18340568   9419821663    191.83       3559        NaN  17440  tdf-2023
1757   18340568   9444280754    179.44       3091        NaN  15792  tdf-2023
1758   18340568   9450520126    159.89       2432        NaN  15062  tdf-2023
1759    5123163   9435838797    174.04       3071        NaN  15427  tdf-2023

         stage    ride_day race_start_day segments  time_delta
0      Stage 1  2023-07-01     2023-07-01       []           0
1      Stage 2  2023-07-02     2023-07-01       []          -1
2      Stage 3  2023-07-03     2023-07-01       []          -2
3      Stage 4  2023-07-04     2023-07-01       []          -3
4      Stage 5  2023-07-05     2023-07-01       []          -4
...        ...         ...            ...      ...         ...
1755   Stage 8  2023-07-08     2023-07-01       []          -7
1756   Stage 9  2023-07-09     2023-07-01       []          -8
1757  Stage 12  2023-07-13     2023-07-01       []         -12
1758  Stage 13  2023-07-14     2023-07-01       []         -13
1759  Stage 10  2023-07-11     2023-07-01       []         -10

[1760 rows x 12 columns]

      strava_id  activity_id  distance  elevation  avg_power   time  \
0       4774417   8825469552    164.29     2516.0        NaN  14404
1       4774417   8835637609    191.93     3132.0        NaN  17583
2       4774417   8855739960    160.41     2564.0        NaN  13879
3       4774417   8856077206    173.84     3118.0        NaN  15754
4       4774417   8856083636    162.60     3183.0        NaN  14420
...         ...          ...       ...        ...        ...    ...
5090   18340568   9300606118     77.24     2443.0        NaN  11874
5091   18340568   9325910220    139.06     3939.0        NaN  20807
5092    5123163   8990988444     92.42      822.0      244.0  11039
5093    5123163   8996259200     58.33      435.0      242.0   5920
5094    5123163   9270587332    193.55     1746.0      271.0  16308

              tour_year  stage    ride_day race_start_day segments  time_delta
0     tdf_training-2023    NaN  2023-04-03     2023-07-01       []          89
1     tdf_training-2023    NaN  2023-04-04     2023-07-01       []          88
2     tdf_training-2023    NaN  2023-04-05     2023-07-01       []          87
3     tdf_training-2023    NaN  2023-04-06     2023-07-01       []          86
4     tdf_training-2023    NaN  2023-04-07     2023-07-01       []          85
...                 ...    ...         ...            ...      ...         ...
5090  tdf_training-2023    NaN  2023-06-20     2023-07-01       []          11
5091  tdf_training-2023    NaN  2023-06-24     2023-07-01       []           7
5092  tdf_training-2023    NaN  2023-05-01     2023-07-01       []          61
5093  tdf_training-2023    NaN  2023-05-02     2023-07-01       []          60
5094  tdf_training-2023    NaN  2023-06-15     2023-07-01       []          16

[5095 rows x 12 columns]

In [18]:
training_data.groupby(by='strava_id').mean(numeric_only=True)

,activity_id,distance,elevation,avg_power,time,stage,time_delta
strava_id,,,,,,,
133606,9.100156e+09,149.177667,2341.700000,NaN,15594.766667,NaN,43.566667
189040,9.105955e+09,100.515000,1334.862500,NaN,11330.300000,NaN,42.450000
254096,9.087039e+09,116.686977,2452.430233,220.542373,13498.953488,NaN,45.581395
259263,9.106697e+09,105.584868,1825.986842,255.840000,11834.000000,NaN,42.657895
288335,9.122544e+09,113.460476,1555.571429,NaN,12860.015873,NaN,39.650794
...,...,...,...,...,...,...,...
25495602,9.118203e+09,102.965672,1636.641791,NaN,11664.507463,NaN,40.552239
29140444,9.189928e+09,147.486500,2329.350000,NaN,14765.900000,NaN,29.000000
36356974,9.124221e+09,105.062609,1285.304348,NaN,11909.565217,NaN,39.608696
37745230,9.059063e+09,105.872456,1930.280702,NaN,12744.175439,NaN,50.157895
49597893,9.113030e+09,114.503438,1859.421875,NaN,11854.437500,NaN,41.453125

In [31]:
training_data[['strava_id', 'distance']].groupby(by='strava_id').mean(numeric_only=True).loc[133606]

distance    149.177667
Name: 133606, dtype: float64

### Loop for counting the number of training sessions

In [ ]:
race_data['no_sessions'] = 0
for k in range(0, len(race_data)):
    try: #count the number of training sessions
        id = race_data['strava_id'][k]
        race_data.loc[k, 'no_sessions'] = \
            len(training_data[training_data['strava_id'] == id])
    except KeyError: #keep 0 as the value
        continue

In [40]:
len(race_data[race_data['no_sessions'] >= 10])

1617

In [39]:
len(race_data)

1806

In [44]:
#keep only those athletes with at least 10 training sessions?
race_data = race_data[race_data['no_sessions'] >= 10]

In [ ]:
# reset the index now that columns have been dropped
race_data = race_data.reset_index().drop(columns=['index'])

### Loop for adding the mean training distance to the race data

In [ ]:
race_data['avg_train_dist'] = 0.0 #cast as float
for k in range(0, len(race_data)):
    id = race_data.loc[k, 'strava_id']
    race_data.loc[k, 'avg_train_dist'] = \
        training_data[['strava_id', 'distance']].groupby(by='strava_id').mean().loc[id,'distance']

### Loop for computing mean average speed

In [66]:
training_data.head()

,strava_id,activity_id,distance,elevation,avg_power,time,tour_year,stage,ride_day,race_start_day,segments,time_delta
0,4774417,8825469552,164.29,2516.0,NaN,14404,tdf_training-2023,NaN,2023-04-03,2023-07-01,[],89
1,4774417,8835637609,191.93,3132.0,NaN,17583,tdf_training-2023,NaN,2023-04-04,2023-07-01,[],88
2,4774417,8855739960,160.41,2564.0,NaN,13879,tdf_training-2023,NaN,2023-04-05,2023-07-01,[],87
3,4774417,8856077206,173.84,3118.0,NaN,15754,tdf_training-2023,NaN,2023-04-06,2023-07-01,[],86
4,4774417,8856083636,162.60,3183.0,NaN,14420,tdf_training-2023,NaN,2023-04-07,2023-07-01,[],85

In [85]:
#compute average speed for a given ride and convert to km/h for interpretability
training_data['average_speed'] = training_data.distance/training_data.time * 3600

for k in range(0, len(race_data)):
    id = race_data.loc[k, 'strava_id']
    race_data.loc[k, 'mean_train_average_speed'] = \
        training_data[['strava_id', 'average_speed']].groupby(by='strava_id').mean().loc[id,'average_speed']

In [86]:
race_data

,strava_id,activity_id,distance,elevation,avg_power,time,tour_year,stage,ride_day,race_start_day,segments,time_delta,avg_train_dist,no_sessions,mean_train_average_speed
0,4774417.0,9.368887e+09,180.58,3262.0,NaN,15739.0,tdf-2023,Stage 1,2023-07-01,2023-07-01,[],0.0,105.124500,60,33.277082
1,4774417.0,9.375430e+09,207.03,2240.0,NaN,17344.0,tdf-2023,Stage 2,2023-07-02,2023-07-01,[],-1.0,105.124500,60,33.277082
2,4774417.0,9.381094e+09,191.93,2394.0,NaN,16979.0,tdf-2023,Stage 3,2023-07-03,2023-07-01,[],-2.0,105.124500,60,33.277082
3,4774417.0,9.387947e+09,181.28,1499.0,NaN,15911.0,tdf-2023,Stage 4,2023-07-04,2023-07-01,[],-3.0,105.124500,60,33.277082
4,4774417.0,9.393654e+09,161.72,3369.0,NaN,14339.0,tdf-2023,Stage 5,2023-07-05,2023-07-01,[],-4.0,105.124500,60,33.277082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,1419979.0,9.512421e+09,117.07,690.0,NaN,11368.0,tdf-2023,Stage 21,2023-07-23,2023-07-01,[],-22.0,103.154667,45,33.188022
1613,18340568.0,9.412475e+09,205.90,1951.0,NaN,16053.0,tdf-2023,Stage 8,2023-07-08,2023-07-01,[],-7.0,129.418667,15,30.369997
1614,18340568.0,9.419822e+09,191.83,3559.0,NaN,17440.0,tdf-2023,Stage 9,2023-07-09,2023-07-01,[],-8.0,129.418667,15,30.369997
1615,18340568.0,9.444281e+09,179.44,3091.0,NaN,15792.0,tdf-2023,Stage 12,2023-07-13,2023-07-01,[],-12.0,129.418667,15,30.369997
1616,18340568.0,9.450520e+09,159.89,2432.0,NaN,15062.0,tdf-2023,Stage 13,2023-07-14,2023-07-01,[],-13.0,129.418667,15,30.369997

In [62]:
training_data[['strava_id', 'distance']].groupby(by='strava_id').mean().loc[4774417]

distance    105.1245
Name: 4774417, dtype: float64

In [60]:
race_data.head()

,strava_id,activity_id,distance,elevation,avg_power,time,tour_year,stage,ride_day,race_start_day,segments,time_delta,avg_train_dist,no_sessions
0,4774417.0,9.368887e+09,180.58,3262.0,NaN,15739.0,tdf-2023,Stage 1,2023-07-01,2023-07-01,[],0.0,1,60
1,4774417.0,9.375430e+09,207.03,2240.0,NaN,17344.0,tdf-2023,Stage 2,2023-07-02,2023-07-01,[],-1.0,1,60
2,4774417.0,9.381094e+09,191.93,2394.0,NaN,16979.0,tdf-2023,Stage 3,2023-07-03,2023-07-01,[],-2.0,1,60
3,4774417.0,9.387947e+09,181.28,1499.0,NaN,15911.0,tdf-2023,Stage 4,2023-07-04,2023-07-01,[],-3.0,1,60
4,4774417.0,9.393654e+09,161.72,3369.0,NaN,14339.0,tdf-2023,Stage 5,2023-07-05,2023-07-01,[],-4.0,1,60

In [ ]:
#I want to include a feature by looking up an athlete's ID number and filling in training data
race_data['avg_train_dist'] = 0
for k in range(0, len(race_data)):
    try: #return the average training distance
        id = race_data['strava_id'][k]
        race_data.loc[k, 'avg_train_dist'] = \
            training_data[['strava_id', 'distance']].groupby(by='strava_id').mean(numeric_only=True).loc[id]
    #except KeyError: #drop the row from the race data if there is no training data for that athlete
        #race_data.drop(labels=)

SyntaxError: incomplete input (1105948688.py, line 4)

In [24]:
training_data.groupby(by='strava_id').count().sort_values(by='activity_id')

,activity_id,distance,elevation,avg_power,time,tour_year,stage,ride_day,race_start_day,segments,time_delta
strava_id,,,,,,,,,,,
3098895,1,1,1,1,1,1,0,1,1,1,1
620617,2,2,2,2,2,2,0,2,2,2,2
3613487,3,3,3,2,3,3,0,3,3,3,3
5123163,3,3,3,3,3,3,0,3,3,3,3
16874183,3,3,3,0,3,3,0,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...
1805247,85,85,85,82,85,85,0,85,85,85,85
254096,86,86,86,59,86,86,0,86,86,86,86
2119306,86,86,86,85,86,86,0,86,86,86,86
19222952,89,89,89,0,89,89,0,89,89,89,89
1905161,109,109,109,106,109,109,0,109,109,109,109

In [5]:
race_data.avg_power.isna().sum()/len(race_data)

np.float64(0.4869318181818182)

In [6]:
print(training_data)
print(race_data)

      strava_id  activity_id  distance  elevation  avg_power   time  \
0       4774417   8825469552    164.29     2516.0        NaN  14404
1       4774417   8835637609    191.93     3132.0        NaN  17583
2       4774417   8855739960    160.41     2564.0        NaN  13879
3       4774417   8856077206    173.84     3118.0        NaN  15754
4       4774417   8856083636    162.60     3183.0        NaN  14420
...         ...          ...       ...        ...        ...    ...
5090   18340568   9300606118     77.24     2443.0        NaN  11874
5091   18340568   9325910220    139.06     3939.0        NaN  20807
5092    5123163   8990988444     92.42      822.0      244.0  11039
5093    5123163   8996259200     58.33      435.0      242.0   5920
5094    5123163   9270587332    193.55     1746.0      271.0  16308

              tour_year  stage    ride_day race_start_day segments  time_delta
0     tdf_training-2023    NaN  2023-04-03     2023-07-01       []          89
1     tdf_training-2023    NaN  2023-04-04     2023-07-01       []          88
2     tdf_training-2023    NaN  2023-04-05     2023-07-01       []          87
3     tdf_training-2023    NaN  2023-04-06     2023-07-01       []          86
4     tdf_training-2023    NaN  2023-04-07     2023-07-01       []          85
...                 ...    ...         ...            ...      ...         ...
5090  tdf_training-2023    NaN  2023-06-20     2023-07-01       []          11
5091  tdf_training-2023    NaN  2023-06-24     2023-07-01       []           7
5092  tdf_training-2023    NaN  2023-05-01     2023-07-01       []          61
5093  tdf_training-2023    NaN  2023-05-02     2023-07-01       []          60
5094  tdf_training-2023    NaN  2023-06-15     2023-07-01       []          16

[5095 rows x 12 columns]

      strava_id  activity_id  distance  elevation  avg_power   time tour_year  \
0       4774417   9368886723    180.58       3262        NaN  15739  tdf-2023
1       4774417   9375430023    207.03       2240        NaN  17344  tdf-2023
2       4774417   9381093872    191.93       2394        NaN  16979  tdf-2023
3       4774417   9387946633    181.28       1499        NaN  15911  tdf-2023
4       4774417   9393653842    161.72       3369        NaN  14339  tdf-2023
...         ...          ...       ...        ...        ...    ...       ...
1755   18340568   9412475152    205.90       1951        NaN  16053  tdf-2023
1756   18340568   9419821663    191.83       3559        NaN  17440  tdf-2023
1757   18340568   9444280754    179.44       3091        NaN  15792  tdf-2023
1758   18340568   9450520126    159.89       2432        NaN  15062  tdf-2023
1759    5123163   9435838797    174.04       3071        NaN  15427  tdf-2023

         stage    ride_day race_start_day segments  time_delta
0      Stage 1  2023-07-01     2023-07-01       []           0
1      Stage 2  2023-07-02     2023-07-01       []          -1
2      Stage 3  2023-07-03     2023-07-01       []          -2
3      Stage 4  2023-07-04     2023-07-01       []          -3
4      Stage 5  2023-07-05     2023-07-01       []          -4
...        ...         ...            ...      ...         ...
1755   Stage 8  2023-07-08     2023-07-01       []          -7
1756   Stage 9  2023-07-09     2023-07-01       []          -8
1757  Stage 12  2023-07-13     2023-07-01       []         -12
1758  Stage 13  2023-07-14     2023-07-01       []         -13
1759  Stage 10  2023-07-11     2023-07-01       []         -10

[1760 rows x 12 columns]

91