In [5]:
import pandas as pd
import numpy as np
import sqlite3

In [6]:
dbfile = '../../grand-tours-resources/data/training.db'
conn = sqlite3.connect(dbfile)
query_all = f"SELECT * FROM stats_data"

df = pd.read_sql_query(query_all, conn)

conn.close()

In [7]:
df.dtypes

activity_id     int64
athlete_id      int64
tour_year      object
stat           object
dtype: object

In [8]:
import ast
df['stat'] = df['stat'].apply(ast.literal_eval)

In [9]:
example_dict = df['stat'][0]

In [10]:
type(example_dict)

dict

In [11]:
example_dict

{'dist': '22.06 km',
 'move_time': '44:23',
 'elevation': '288 m',
 'avg_max': 'Speed 29.8 km/h 63.6 km/h',
 'elapsed': '44:57',
 'temp': '2 ℃',
 'humd': '85%',
 'feels': '1 ℃',
 'wind_speed': '6.1 km/h',
 'wind_direction': 'ESE',
 'device': 'Wahoo ELEMNT BOLT'}

In [12]:
def get_dict_value(x, key):
    try:
        return x[key]
    except:
        return None

In [13]:
for key in example_dict.keys():
    df[key] = df['stat'].apply(lambda x: get_dict_value(x, key))

In [14]:
df

,activity_id,athlete_id,tour_year,stat,dist,move_time,elevation,avg_max,elapsed,temp,humd,feels,wind_speed,wind_direction,device
0,6929029131,1821678,tdf_training-2022,"{'dist': '22.06 km', 'move_time': '44:23', 'el...",22.06 km,44:23,288 m,Speed 29.8 km/h 63.6 km/h,44:57,2 ℃,85%,1 ℃,6.1 km/h,ESE,Wahoo ELEMNT BOLT
1,6929045458,31541211,tdf_training-2022,"{'dist': '26.08 km', 'move_time': '56:43', 'el...",26.08 km,56:43,77 m,Speed 27.6 km/h 42.3 km/h,56:43,4 ℃,81%,-1 ℃,26.6 km/h,SW,Wahoo ELEMNT ROAM
2,6929345937,18885405,tdf_training-2022,"{'dist': '0 km', 'move_time': '1:21:00', 'wap'...",0 km,1:21:00,None,Speed 0.0 km/h 0.0 km/h,1:21:00,None,None,None,None,None,Garmin Edge 830
3,6929400023,14762808,tdf_training-2022,"{'dist': '0.08 km', 'move_time': '34:08', 'wap...",0.08 km,34:08,None,Speed 0.2 km/h 21.7 km/h,34:08,None,None,None,None,None,Wahoo ELEMNT BOLT
4,6929407944,4018952,tdf_training-2022,"{'dist': '56.89 km', 'move_time': '2:00:13', '...",56.89 km,2:00:13,524 m,Speed 28.4 km/h 58.3 km/h,2:04:23,6 ℃,75%,3 ℃,22.9 km/h,WSW,Garmin Edge 520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16315,13697679030,1557033,tdf_training-2022,"{'dist': '179.12 km', 'move_time': '4:19:41', ...",179.12 km,4:19:41,"2,839 m",Speed 41.4 km/h 94.8 km/h,4:20:02,16 ℃,69%,16 ℃,14.2 km/h,NW,Wahoo ELEMNT ROAM
16316,13697722014,189040,tdf_training-2022,"{'dist': '177.86 km', 'move_time': '4:14:57', ...",177.86 km,4:14:57,"2,816 m",Speed 41.9 km/h 88.5 km/h,4:15:25,16 ℃,69%,16 ℃,14.2 km/h,NW,Garmin Edge 840
16317,13697743934,133606,tdf_training-2022,"{'dist': '178.63 km', 'move_time': '4:18:47', ...",178.63 km,4:18:47,"2,710 m",Speed 41.4 km/h 93.1 km/h,4:18:47,16 ℃,69%,16 ℃,14.2 km/h,NW,Garmin Edge 840
16318,13698889798,6137589,tdf_training-2022,"{'dist': '179.76 km', 'move_time': '4:20:15', ...",179.76 km,4:20:15,"2,725 m",Speed 41.4 km/h 96.2 km/h,4:22:07,16 ℃,69%,16 ℃,14.2 km/h,NW,Wahoo ELEMNT BOLT
16319,13698890701,6137589,tdf_training-2022,"{'dist': '22.56 km', 'move_time': '39:57', 'el...",22.56 km,39:57,142 m,Speed 33.9 km/h 53.1 km/h,41:13,18 ℃,58%,16 ℃,17.8 km/h,WNW,Wahoo ELEMNT BOLT

In [15]:
df.columns

Index(['activity_id', 'athlete_id', 'tour_year', 'stat', 'dist', 'move_time',
       'elevation', 'avg_max', 'elapsed', 'temp', 'humd', 'feels',
       'wind_speed', 'wind_direction', 'device'],
      dtype='object')

In [16]:
df = df.rename(columns={'dist': 'dist_km', 'elevation': 'elevation_m', 'temp': 'temp_C', 'humd': 'humd_%', 'wind_speed': 'wind_speed_kmh'})

In [17]:
df.dropna()

,activity_id,athlete_id,tour_year,stat,dist_km,move_time,elevation_m,avg_max,elapsed,temp_C,humd_%,feels,wind_speed_kmh,wind_direction,device
0,6929029131,1821678,tdf_training-2022,"{'dist': '22.06 km', 'move_time': '44:23', 'el...",22.06 km,44:23,288 m,Speed 29.8 km/h 63.6 km/h,44:57,2 ℃,85%,1 ℃,6.1 km/h,ESE,Wahoo ELEMNT BOLT
1,6929045458,31541211,tdf_training-2022,"{'dist': '26.08 km', 'move_time': '56:43', 'el...",26.08 km,56:43,77 m,Speed 27.6 km/h 42.3 km/h,56:43,4 ℃,81%,-1 ℃,26.6 km/h,SW,Wahoo ELEMNT ROAM
4,6929407944,4018952,tdf_training-2022,"{'dist': '56.89 km', 'move_time': '2:00:13', '...",56.89 km,2:00:13,524 m,Speed 28.4 km/h 58.3 km/h,2:04:23,6 ℃,75%,3 ℃,22.9 km/h,WSW,Garmin Edge 520
6,6929491976,36356974,tdf_training-2022,"{'dist': '32.62 km', 'move_time': '1:07:10', '...",32.62 km,1:07:10,125 m,Speed 29.1 km/h 46.7 km/h,1:09:54,6 ℃,75%,1 ℃,39.7 km/h,WSW,Garmin Edge 1030
7,6929519729,2542098,tdf_training-2022,"{'dist': '87.30 km', 'move_time': '3:07:12', '...",87.30 km,3:07:12,979 m,Speed 28.0 km/h 58.0 km/h,3:11:02,6 ℃,93%,1 ℃,31.4 km/h,WNW,Bryton Rider S500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16315,13697679030,1557033,tdf_training-2022,"{'dist': '179.12 km', 'move_time': '4:19:41', ...",179.12 km,4:19:41,"2,839 m",Speed 41.4 km/h 94.8 km/h,4:20:02,16 ℃,69%,16 ℃,14.2 km/h,NW,Wahoo ELEMNT ROAM
16316,13697722014,189040,tdf_training-2022,"{'dist': '177.86 km', 'move_time': '4:14:57', ...",177.86 km,4:14:57,"2,816 m",Speed 41.9 km/h 88.5 km/h,4:15:25,16 ℃,69%,16 ℃,14.2 km/h,NW,Garmin Edge 840
16317,13697743934,133606,tdf_training-2022,"{'dist': '178.63 km', 'move_time': '4:18:47', ...",178.63 km,4:18:47,"2,710 m",Speed 41.4 km/h 93.1 km/h,4:18:47,16 ℃,69%,16 ℃,14.2 km/h,NW,Garmin Edge 840
16318,13698889798,6137589,tdf_training-2022,"{'dist': '179.76 km', 'move_time': '4:20:15', ...",179.76 km,4:20:15,"2,725 m",Speed 41.4 km/h 96.2 km/h,4:22:07,16 ℃,69%,16 ℃,14.2 km/h,NW,Wahoo ELEMNT BOLT
16319,13698890701,6137589,tdf_training-2022,"{'dist': '22.56 km', 'move_time': '39:57', 'el...",22.56 km,39:57,142 m,Speed 33.9 km/h 53.1 km/h,41:13,18 ℃,58%,16 ℃,17.8 km/h,WNW,Wahoo ELEMNT BOLT

In [18]:
df.isna().sum()

activity_id          0
athlete_id           0
tour_year            0
stat                 0
dist_km              1
move_time          117
elevation_m        628
avg_max             39
elapsed             39
temp_C            1655
humd_%            1655
feels             1655
wind_speed_kmh    1655
wind_direction    1655
device               0
dtype: int64

In [19]:
len(df.dropna())/len(df)

0.8938725490196079

In [20]:
df.drop(labels='stat', axis=1)

,activity_id,athlete_id,tour_year,dist_km,move_time,elevation_m,avg_max,elapsed,temp_C,humd_%,feels,wind_speed_kmh,wind_direction,device
0,6929029131,1821678,tdf_training-2022,22.06 km,44:23,288 m,Speed 29.8 km/h 63.6 km/h,44:57,2 ℃,85%,1 ℃,6.1 km/h,ESE,Wahoo ELEMNT BOLT
1,6929045458,31541211,tdf_training-2022,26.08 km,56:43,77 m,Speed 27.6 km/h 42.3 km/h,56:43,4 ℃,81%,-1 ℃,26.6 km/h,SW,Wahoo ELEMNT ROAM
2,6929345937,18885405,tdf_training-2022,0 km,1:21:00,None,Speed 0.0 km/h 0.0 km/h,1:21:00,None,None,None,None,None,Garmin Edge 830
3,6929400023,14762808,tdf_training-2022,0.08 km,34:08,None,Speed 0.2 km/h 21.7 km/h,34:08,None,None,None,None,None,Wahoo ELEMNT BOLT
4,6929407944,4018952,tdf_training-2022,56.89 km,2:00:13,524 m,Speed 28.4 km/h 58.3 km/h,2:04:23,6 ℃,75%,3 ℃,22.9 km/h,WSW,Garmin Edge 520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16315,13697679030,1557033,tdf_training-2022,179.12 km,4:19:41,"2,839 m",Speed 41.4 km/h 94.8 km/h,4:20:02,16 ℃,69%,16 ℃,14.2 km/h,NW,Wahoo ELEMNT ROAM
16316,13697722014,189040,tdf_training-2022,177.86 km,4:14:57,"2,816 m",Speed 41.9 km/h 88.5 km/h,4:15:25,16 ℃,69%,16 ℃,14.2 km/h,NW,Garmin Edge 840
16317,13697743934,133606,tdf_training-2022,178.63 km,4:18:47,"2,710 m",Speed 41.4 km/h 93.1 km/h,4:18:47,16 ℃,69%,16 ℃,14.2 km/h,NW,Garmin Edge 840
16318,13698889798,6137589,tdf_training-2022,179.76 km,4:20:15,"2,725 m",Speed 41.4 km/h 96.2 km/h,4:22:07,16 ℃,69%,16 ℃,14.2 km/h,NW,Wahoo ELEMNT BOLT
16319,13698890701,6137589,tdf_training-2022,22.56 km,39:57,142 m,Speed 33.9 km/h 53.1 km/h,41:13,18 ℃,58%,16 ℃,17.8 km/h,WNW,Wahoo ELEMNT BOLT

Here, we clean up the columns by removing non-numerical data. For now, we'll crudely drop all rows with null data

In [21]:
df_dropped = df.dropna()

In [22]:
#Check progress:
df_dropped

,activity_id,athlete_id,tour_year,stat,dist_km,move_time,elevation_m,avg_max,elapsed,temp_C,humd_%,feels,wind_speed_kmh,wind_direction,device
0,6929029131,1821678,tdf_training-2022,"{'dist': '22.06 km', 'move_time': '44:23', 'el...",22.06 km,44:23,288 m,Speed 29.8 km/h 63.6 km/h,44:57,2 ℃,85%,1 ℃,6.1 km/h,ESE,Wahoo ELEMNT BOLT
1,6929045458,31541211,tdf_training-2022,"{'dist': '26.08 km', 'move_time': '56:43', 'el...",26.08 km,56:43,77 m,Speed 27.6 km/h 42.3 km/h,56:43,4 ℃,81%,-1 ℃,26.6 km/h,SW,Wahoo ELEMNT ROAM
4,6929407944,4018952,tdf_training-2022,"{'dist': '56.89 km', 'move_time': '2:00:13', '...",56.89 km,2:00:13,524 m,Speed 28.4 km/h 58.3 km/h,2:04:23,6 ℃,75%,3 ℃,22.9 km/h,WSW,Garmin Edge 520
6,6929491976,36356974,tdf_training-2022,"{'dist': '32.62 km', 'move_time': '1:07:10', '...",32.62 km,1:07:10,125 m,Speed 29.1 km/h 46.7 km/h,1:09:54,6 ℃,75%,1 ℃,39.7 km/h,WSW,Garmin Edge 1030
7,6929519729,2542098,tdf_training-2022,"{'dist': '87.30 km', 'move_time': '3:07:12', '...",87.30 km,3:07:12,979 m,Speed 28.0 km/h 58.0 km/h,3:11:02,6 ℃,93%,1 ℃,31.4 km/h,WNW,Bryton Rider S500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16315,13697679030,1557033,tdf_training-2022,"{'dist': '179.12 km', 'move_time': '4:19:41', ...",179.12 km,4:19:41,"2,839 m",Speed 41.4 km/h 94.8 km/h,4:20:02,16 ℃,69%,16 ℃,14.2 km/h,NW,Wahoo ELEMNT ROAM
16316,13697722014,189040,tdf_training-2022,"{'dist': '177.86 km', 'move_time': '4:14:57', ...",177.86 km,4:14:57,"2,816 m",Speed 41.9 km/h 88.5 km/h,4:15:25,16 ℃,69%,16 ℃,14.2 km/h,NW,Garmin Edge 840
16317,13697743934,133606,tdf_training-2022,"{'dist': '178.63 km', 'move_time': '4:18:47', ...",178.63 km,4:18:47,"2,710 m",Speed 41.4 km/h 93.1 km/h,4:18:47,16 ℃,69%,16 ℃,14.2 km/h,NW,Garmin Edge 840
16318,13698889798,6137589,tdf_training-2022,"{'dist': '179.76 km', 'move_time': '4:20:15', ...",179.76 km,4:20:15,"2,725 m",Speed 41.4 km/h 96.2 km/h,4:22:07,16 ℃,69%,16 ℃,14.2 km/h,NW,Wahoo ELEMNT BOLT
16319,13698890701,6137589,tdf_training-2022,"{'dist': '22.56 km', 'move_time': '39:57', 'el...",22.56 km,39:57,142 m,Speed 33.9 km/h 53.1 km/h,41:13,18 ℃,58%,16 ℃,17.8 km/h,WNW,Wahoo ELEMNT BOLT

In [23]:
df_dropped_copy = df_dropped.copy()

In [24]:
#bad but maybe useful for now
df_dropped = df_dropped_copy

In [25]:
#Cleanup of the distance column
df_dropped.loc[:,'dist_km'] = df_dropped.loc[:,'dist_km'].apply(lambda str: str.removesuffix(' km'))

In [26]:
#Cleanup of elevation. Also requires removal of commas
df_dropped.loc[:, 'elevation_m'] = df_dropped.loc[:, 'elevation_m'].apply(lambda str: str.removesuffix(' m').replace(',', ''))

In [27]:
#Cleanup of humidity
df_dropped.loc[:, 'humd_%'] = df_dropped.loc[:, 'humd_%'].apply(lambda str: str.removesuffix('%'))

In [28]:
#Cleanup of temp_C
df_dropped.loc[:, 'temp_C'] = df_dropped.loc[:, 'temp_C'].apply(lambda str: str.removesuffix(' ℃'))

In [29]:
#Cleanup of feels
df_dropped.loc[:, 'feels'] = df_dropped.loc[:, 'feels'].apply(lambda str: str.removesuffix(' ℃'))

In [30]:
#Cleanup of wind speed
df_dropped.loc[:, 'wind_speed_kmh'] = df_dropped.loc[:, 'wind_speed_kmh'].apply(lambda str: str.removesuffix(' km/h'))

In [31]:
df_dropped.dtypes

activity_id        int64
athlete_id         int64
tour_year         object
stat              object
dist_km           object
move_time         object
elevation_m       object
avg_max           object
elapsed           object
temp_C            object
humd_%            object
feels             object
wind_speed_kmh    object
wind_direction    object
device            object
dtype: object

In [32]:
#Cleanup of the avg_max column
example_str = df_dropped['avg_max'][0]
example_str.split()

['Speed', '29.8', 'km/h', '63.6', 'km/h']

In [33]:
df_dropped = df_dropped.reset_index()

In [34]:
for k, str in enumerate(df_dropped['avg_max']):
    split = str.split()
    if len(split) != 5:
        print(f'Improper string found at position {k}: ' + str)

Improper string found at position 2779: Elapsed Time 4:21:05
Improper string found at position 7173: Elapsed Time 1:35:07
Improper string found at position 10429: Elapsed Time 1:37:56
Improper string found at position 12145: Elapsed Time 4:36:47

In [35]:
df_dropped = df_dropped.drop(labels=[2779, 7173, 10429, 12145]).reset_index()

In [36]:
df_dropped.loc[:,'avg_kmh'] = df_dropped.loc[:, 'avg_max'].str.split().apply(lambda str: str[1])

In [37]:
df_dropped.loc[:, 'max_kmh'] = df_dropped.loc[:, 'avg_max'].str.split().apply(lambda str: str[3].replace(',', ''))

In [38]:
#convert columns that should be numeric but are currently recorded as strings
#trying to update the columns with the types one at a time did not work for some reason
numeric_columns = ['dist_km', 'elevation_m', 'humd_%', 'temp_C', 'feels', 'wind_speed_kmh', 'avg_kmh', 'max_kmh']

df_dropped[numeric_columns] = df_dropped[numeric_columns].apply(pd.to_numeric)

In [39]:
df_dropped.dtypes

level_0             int64
index               int64
activity_id         int64
athlete_id          int64
tour_year          object
stat               object
dist_km           float64
move_time          object
elevation_m         int64
avg_max            object
elapsed            object
temp_C              int64
humd_%              int64
feels               int64
wind_speed_kmh    float64
wind_direction     object
device             object
avg_kmh           float64
max_kmh           float64
dtype: object

In [ ]:
#I hate this fix so much

def time_formatter(time_string):
    time_string = time_string.removesuffix('s')
    if len(time_string) == 1:
        time_string = '00:00:0' + time_string
    elif len(time_string) == 2:
        time_string = '00:00:' + time_string
    elif len(time_string) == 3:
        time_string = '00:00' + time_string
    elif len(time_string) == 4:
        time_string = '00:0' + time_string
    elif len(time_string) == 5:
        time_string = '00:' + time_string
    elif len(time_string) == 6:
        time_string = '00' + time_string
    return time_string

In [ ]:
#df_dropped[['move_time', 'elapsed']] = pd.to_timedelta(df_dropped[['move_time', 'elapsed']], format=)

In [306]:
time_series = df_dropped['move_time']

In [307]:
time_series

0          44:23
1          56:43
2        2:00:13
3        1:07:10
4        3:07:12
          ...
14579    4:19:41
14580    4:14:57
14581    4:18:47
14582    4:20:15
14583      39:57
Name: move_time, Length: 14584, dtype: object

In [318]:
time_series.apply(len).value_counts()

move_time
7    13099
5     1210
4      188
2       53
3       34
Name: count, dtype: int64

In [ ]:
time_series.loc['move_time']

In [352]:
formatted_series = time_series.apply(time_formatter)

In [359]:
pd.to_timedelta(formatted_series).dt.seconds

0         2663
1         3403
2         7213
3         4030
4        11232
         ...
14579    15581
14580    15297
14581    15527
14582    15615
14583     2397
Name: move_time, Length: 14584, dtype: int32

In [360]:
formatted_series[14579]

'04:19:41'

In [361]:
3600*4+60*19+41

15581